### ISSUE TITLE
weird tracefile created

### ISSUE THREAD

**Issue by xbenji** [Burgestrand/Hallon#125] opened 2012-06-27 06:46 UTC
Hey,

I sometimes have this error displayed right after I create a session and start load my playlists:

`[CANT_OPEN_TRACE_FILE] Unable to open trace file (26)`

I also noticed every time I launch my app (actually using this code in rake task) there's this a weird file created in the working dir with a wrong encoded name : 
`�� (invalid encoding)` in my file manager, a `ls -altr` gives me

```
...
-rw-rw-r--  1 ben ben 36368354 Jun 26 23:19 `?X?
...
```

This file seems to be the tracefile itself, i'm able to open it and goes like this (80MB):

```
libspotify trace from 12.1.51.g86c92b43 Release Linux-x86_64 

< sp_session_create() = 0
> sp_session_login(0x45a2840 'xbenji' '<hidden>' 0) on 0x7fc2987cf700
> sp_session_connectionstate(0x45a2840) on 0x7fc2987cf700
>< sp_session_connectionstate() = 0 
...
```

I'm surprised it's there since I don't use the `:tracefile` param when I create my session :

``` ruby
session = Hallon::Session.initialize IO.read('spotify_appkey.key')
```

I even tried to 'force' the parameter in the option hash, but has no effect.

``` ruby
session = Hallon::Session.initialize(IO.read('spotify_appkey.key'), { :tracefile => nil })
```

The initial `[CANT_OPEN_TRACE_FILE]` doesn't happen all the time, it works eventually when I rerun my task after several tries or delete the tracefiles, but it keeps coming back, and its name seems random. I have this problem since I update my bundle (switching from libspotify 10 to 12), and also occurs when deployed to heroku.

Any idea of what could be wrong here :( ?

**Comment by Burgestrand** [comment] 2012-06-27 08:40
This is an interesting issue, and I’ve found the cause.

On some platforms (for example Linux), certain data types are differently laid out as opposed to, for example, Mac OS X, which is my main development platform. I was lucky to catch [a session configuration setting unknown to me in the online documentation](https://developer.spotify.com/technologies/libspotify/docs/12.1.45/structsp__session__config.html#a4a94ad4270e5401e68587952661bd3ca).

This means that on all platforms that support the `ca_certs_filename` session configuration, this issue might crop up randomly. However, on Mac OS X it will always work as expected!

I’ll have to remedy this issue by being more specific in which platforms of libspotify that Hallon actually support. Will have to make a new release of the [spotify gem](http://rubygems.org/gems/spotify) to solve the issue.

So, bug confirmed, found, and will be fixed. I’ll close this issue when the bugfix is out and available. :)

**Comment by Burgestrand** [comment] 2012-06-28 06:29
Until I’ve implemented the actual fix (which requires platform detection and a new release of the spotify gem) here’s a snippet that you can use in the meanwhile, like this:

``` ruby
require 'hallon'

# This is the important part of the snippet.
module Spotify
  class SessionConfig
    layout :api_version, :int,
           :cache_location, :string_pointer,
           :settings_location, :string_pointer,
           :application_key, :pointer,
           :application_key_size, :size_t,
           :user_agent, :string_pointer,
           :callbacks, SessionCallbacks.by_ref,
           :userdata, :userdata,
           :compress_playlists, :bool,
           :dont_save_metadata_for_playlists, :bool,
           :initially_unload_playlists, :bool,
           :device_id, :string_pointer,
           :proxy, :string_pointer,
           :proxy_username, :string_pointer,
           :proxy_password, :string_pointer,
           :ca_certs_filename, :string_pointer,
           :tracefile, :string_pointer
  end
end
# The above snippet should only be written *after* Hallon has been required.

session = Hallon::Session.initialize IO.read(…)
```

Use that code _after_ you’ve required Hallon. It will redefine the layout of the session configuration so that the missing option is also accounted for. It should stop the random tracefiles appearing. It won’t allow you to set the `ca_certs_filename` option in Session.initialize, however.

**Comment by xbenji** [comment] 2012-06-28 22:59
Thanks for investigating this!

I'll will give it a try as soon as I can

**Closed as completed** 2012-07-02 14:12 UTC
Labels: Bug

**Comment by Burgestrand** [comment] 2012-07-02 14:14
Hi!

I’ve pushed a new release of the Spotify gem, a new release of Hallon (new release of Spotify gem broke backwards compatibility with ruby 1.8) which should have the fix available. The ability to configure the ca_certs_filename for proxy connections is not implemented, that’ll come in a later release.

So, Hallon v0.18.0 should have this issue solved.
